var codes = {
    100: 'Continue',
    101: 'Switching Protocols',
    102: 'Processing',
    103: 'Early Hints',
    200: 'OK',
    201: 'Created',
    202: 'Accepted',
    203: 'Non-Authoritative Information',
    204: 'No Content',
    205: 'Reset Content',
    206: 'Partial Content',
    207: 'Multi-Status',
    208: 'Already Reported',
    226: 'IM Used',
    300: 'Multiple Choices',
    301: 'Moved Permanently',
    302: 'Moved temporarily',
    303: 'See Other',
    304: 'Not Modified',
    305: 'Use Proxy',
    306: 'Switch Proxy',
    307: 'Temporary Redirect',
    308: 'Permanent Redirect',
    400: 'Bad Request',
    401: 'Unauthorized',
    402: 'Payment Required',
    403: 'Forbidden',
    404: 'Not Found',
    405: 'Method Not Allowed',
    406: 'Not Acceptable',
    407: 'Proxy Authentication Required',
    408: 'Request Timeout',
    409: 'Conflict',
    410: 'Gone',
    411: 'Length Required',
    412: 'Precondition Failed',
    413: 'Payload Too Large',
    414: 'URI Too Long',
    415: 'Unsupported Media Type',
    416: 'Range Not Satisfiable',
    417: 'Expectation Failed',
    418: "I'm a teapot",
    421: 'Misdirected Request',
    422: 'Unprocessable Content',
    423: 'Locked',
    424: 'Failed Dependency',
    425: 'Too Early',
    426: 'Upgrade Required',
    428: 'Precondition Required',
    429: 'Too Many Requests',
    431: 'Request Header Fields Too Large',
    451: 'Unavailable For Legal Reasons',
    500: 'Internal Server Error',
    501: 'Not Implemented',
    502: 'Bad Gateway',
    503: 'Service Unavailable',
    504: 'Gateway Timeout',
    505: 'HTTP Version Not Supported',
    506: 'Variant Also Negotiates',
    507: 'Insufficient Storage',
    508: 'Loop Detected',
    510: 'Not Extended',
    511: 'Network Authentication Required',

    218: 'This is fine (Apache HTTP Server)',
    419: 'Page Expired (Laravel Framework)',
    420: 'Method Failure (Spring Framework)',
    420: 'Enhance Your Calm (Twitter)',
    430: 'Request Header Fields Too Large (Shopify)',
    430: 'Shopify Security Rejection (Shopify)',
    450: 'Blocked by Windows Parental Controls (Microsoft)',
    498: 'Invalid Token (Esri)',
    499: 'Token Required (Esri)',
    509: 'Bandwidth Limit Exceeded (Apache Web Server/cPanel)',
    529: 'Site is overloaded (Pantheon Systems)',
    530: 'Site is frozen (Pantheon Systems)',
    530: 'Origin DNS Error (Shopify)',
    540: 'Temporarily Disabled (Shopify)',
    598: '(Informal convention) Network read timeout error',
    599: 'Network Connect Timeout Error',
    783: 'Unexpected Token (Shopify)',
    999: 'Non-standard (LinkedIn)',

    440: 'Login Time-out (IIS)',
    449: 'Retry With (IIS)',
    451: 'Redirect (IIS)',

    444: 'No Response (nginx)',
    494: 'Request header too large (nginx)',
    495: 'SSL Certificate Error (nginx)',
    496: 'SSL Certificate Required (nginx)',
    497: 'HTTP Request Sent to HTTPS Port (nginx)',
    499: 'Client Closed Request (nginx)',

    520: 'Web Server Returned an Unknown Error (Cloudflare)',
    521: 'Web Server Is Down (Cloudflare)',
    522: 'Connection Timed Out (Cloudflare)',
    523: 'Origin Is Unreachable (Cloudflare)',
    524: 'A Timeout Occurred (Cloudflare)',
    525: 'SSL Handshake Failed (Cloudflare)',
    526: 'Invalid SSL Certificate (Cloudflare)',
    527: 'Railgun Error (obsolete) (Cloudflare)',
    530: '1xxx error',

    '000': 'compressed length of any of the headers exceeds 8K bytes or if more than 10K requests are served through one connection',
    460: 'Client closed the connection with the load balancer before the idle timeout period elapsed',
    463: 'The load balancer received an X-Forwarded-For request header with more than 30 IP addresses',
    464: 'Incompatible protocol versions between Client and Origin server',
    561: 'Unauthorized',

    110: 'Response is Stale',
    111: 'Revalidation Failed',
    112: 'Disconnected Operation',
    113: 'Heuristic Expiration',
    199: 'Miscellaneous Warning',
    214: 'Transformation Applied',
    299: 'Miscellaneous Persistent Warning',
}

export default { keys: Object.keys(codes), codes: codes };